import numpy as np
from cffi import FFI
ffi = FFI()


#fixed model parameters (add more depending on the WI model):
#The values here should match the find_ICs.py values
gst = 100.0 
V0 = 1e-14

#Upsilon parameters
p = int(3)
c = int(0)

hybrid_inf = int(0)
#ph_crit = M/g

#Other fixed parameters:
therm = int(0) #Enable thermalization with 1 and disable with 0
rad_noise = int(0) #Enable noise term in radiation perturbation equation with 1 and disable with 0
Nrealz = 2048 #number of realizations to average over
verbosity = int(0) #0 for no error logging
Nstar = 7.0 #e-fold at which to evaluate the power-spectrum

#loads the initial conditions file generated by find_ICs.py
phi_ini,Qini = np.loadtxt("ics.dat",unpack=True,delimiter=",")

#Modify this according to the model_calc.cpp "model" function signature (copy-paste the arguments of "void model" in pert/model_calc.cpp). Nothing else needs to be modified here.
ffi.cdef("void model (double phi_ini,double Q_ini, double gst, double V0, int p, int c, int therm, int rad_noise,int hybrid_inf) ; void clear_vars();void set_phi_crit (double x);extern double Nend;extern double GQ_val;extern double Q_val; void set_globals (int N_realizations, double Nstar, int verbosity);",override=True)

lib_pert = ffi.dlopen("./pert/libpert.so") #opens the compiled C++ binary

#set global variables
lib_pert.set_globals(Nrealz,Nstar,verbosity)

#For hybrid inflation
if hybrid_inf==1:
    lib_pert.set_phi_crit(ph_crit)

for i,j in zip(phi_ini,Qini):
    lib_pert.model(i,j,gst,V0,p,c,therm,rad_noise,hybrid_inf) #Modify to match the signature of the C++ library
    GQ = lib_pert.GQ_val
    Q = lib_pert.Q_val
    lib_pert.clear_vars()
    print(f"Calculating GQ at Q= {Q}")
    with open('GQ.dat', 'a') as fl:
        fl.write(str(Q)+","+str(GQ)+"\n")
